name: Build

on:
  workflow_dispatch:
  pull_request:
  
permissions:
  contents: read 
  packages: read

jobs:
  setup:
    runs-on: ["self-hosted", "run-${{github.run_id}}"]
    steps:
      - name: Install .NET to Device
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x.x"

      - name: Clone and Checkout the Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true

      - name: Run .NET Restore to reload NuGet Packages
        run: dotnet restore

      - name: Create Websites Folder
        shell: bash
        run: mkdir Build
   
  build-nuget:
    runs-on: ["self-hosted", "run-${{github.run_id}}"]
    needs: setup
    steps:
      - name: Build for NuGet 
        shell: bash
        run: dotnet build ${{ github.event.repository.name }}.Library/${{ github.event.repository.name }}.Library.csproj -c Release -f net8.0

      - name: Pack for NuGet
        id: pack-nuget
        shell: bash
        run: dotnet pack -c Release --no-restore --no-build 

  build-source:
    needs: setup
    runs-on: ["self-hosted", "run-${{github.run_id}}"]
    strategy:
      matrix:
        platforms: ["win-x64", "linux-x64"]
    steps:
      - name: Build as Standalone Source
        shell: bash
        run: dotnet publish ${{ github.event.repository.name }}.Application/${{ github.event.repository.name }}.Application.csproj -c Release -r "${{ matrix.platforms }}" --self-contained true

  upload-source:
    runs-on: ["self-hosted", "run-${{github.run_id}}"]
    needs: [build-source]
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        platforms: ["win-x64", "linux-x64"]
    steps:
      - name: Compress Standalone Source
        shell: bash
        run: tar -czf ./Build/${{ github.event.repository.name }}-${{ matrix.platforms }}.tar.gz -C ${{ github.event.repository.name }}.Application/bin/Release/net8.0/${{ matrix.platforms }}/publish .